baseURL = "https://mochieer.tech"
languageCode = "ja"
title = "mochieer.tech"
theme = "whoami"
paginate = 5
hasCJKLanguage = true
buildFuture = true

[menu]
  [[menu.main]]
    identifier = "top"
    name = "mochieer.tech"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "記事一覧"
    url = "/posts/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
