baseURL = "https://mochieer.tech"
languageCode = "ja"
title = "mochieer.tech"
theme = "whoami"
paginate = 5
hasCJKLanguage = true
buildFuture = true
copyright = "(c) mochieer"

[params]
  [params.author]
    name = "mochieer"
    email = "mochieer@gmail.com"
    twitter = "mochieer"

  [params.github]
    url = "https://github.com/mochieer/mochieer.tech"
    branch = "main"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "記事一覧"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "タグ一覧"
    url = "/tags/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    startInline = true
